### ISSUE TITLE
how install for Debian Gnu/Linux??

### ISSUE THREAD

**Issue by birdofprey** [facebook/openr#1]
how install for Debian Gnu/Linux,give me hope the help ...

**Comment by saifhhasan** [comment]
We internally use CentOS and maintain build for Ubuntu (widely used distribution out there). I would encourage you to try out and install all dependencies of OpenR, following `build/build_openr.sh` script, and try to compile OpenR.

It should work on it. It is just the matter of installing all dependencies :) We would be happy to pull in your debian build script if you happen to get one out.
