### ISSUE TITLE
About:run_openr.sh

### ISSUE THREAD

**Issue by nxppru** [facebook/openr#15]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue Description

/etc/sysconfig/openr No files or folders

# Environment

* OS version: <e.g. ubuntu-16.04>
...

# Minimal test code / Steps to reproduce the issue
Run OpenR

$ run_openr.sh

You can also pass in a custom configuration file and override/add openr flags:

$ run_openr.sh --help
USAGE: run_openr.sh [config_file_path] [openr_flags]
If config_file_path is not provided, we will source the one at /etc/sysconfig/openr
If openr_flags are provided, they will be passed along to openr and override any passed by this script

# What's the actual result?

zy@zy-pc:~/openr/openr/scripts$ ./run_openr.sh
./run_openr.sh: line 77: /etc/sysconfig/openr: 没有那个文件或目录<No files or folders>
Configuration not found at /etc/sysconfig/openr. Using default configuration
openr[25418]: Starting OpenR daemon.
I1221 18:27:36.451370 25421 Main.cpp:366] Starting Watchdog thread ...
I1221 18:27:36.452584 25418 FunctionScheduler.cpp:324] Starting FunctionScheduler with 0 functions.
I1221 18:27:36.453409 25423 NetlinkSystemHandler.cpp:114] Initializng Netlink from server thread
I1221 18:27:36.453805 25423 Main.cpp:409] Starting NetlinkSystem server...
I1221 18:27:36.454073 25423 ThriftServer.cpp:261] libevent 2.0.21-stable method epoll
I1221 18:27:36.458585 25424 Main.cpp:433] Starting ConfigStore thread...
I1221 18:27:36.464072 25425 Main.cpp:453] Starting ZmqMonitor thread...
I1221 18:27:36.472856 25426 Main.cpp:478] Starting KvStore thread...
I1221 18:27:36.475240 25418 PrefixManager.cpp:68] Successfully loaded prefixes from disk
I1221 18:27:36.475607 25418 PrefixManager.cpp:105] writing my prefix to KvStore prefix:zy-pc
I1221 18:27:36.480376 25428 Main.cpp:502] Starting the PrefixManager thread...
E1221 18:27:36.480763 25418 KnownKeysStore.cpp:24] Failed reading known keys, file might be missing
I1221 18:27:36.487848 25429 Main.cpp:569] Starting the spark thread...
I1221 18:27:36.489207 25418 LinkMonitor.cpp:149] Loading link-monitor config
I1221 18:27:36.491371 25429 Spark.cpp:425] Constructing Spark server for node zy-pc
I1221 18:27:36.493424 25435 PosixThreadFactory.cpp:194] setpriority failed (are you root?) with error 13: Permission denied
I1221 18:27:36.493664 25434 PosixThreadFactory.cpp:194] setpriority failed (are you root?) with error 13: Permission denied
I1221 18:27:36.493795 25433 PosixThreadFactory.cpp:194] setpriority failed (are you root?) with error 13: Permission denied
I1221 18:27:36.493713 25429 Spark.cpp:548] Spark thread attaching socket/events callbacks...
I1221 18:27:36.494040 25430 PosixThreadFactory.cpp:194] setpriority failed (are you root?) with error 13: Permission denied
I1221 18:27:36.497334 25432 PosixThreadFactory.cpp:194] setpriority failed (are you root?) with error 13: Permission denied
I1221 18:27:36.500648 25423 ThriftServer.cpp:393] Using 0 SSL handshake threads
I1221 18:27:36.501008 25418 LinkMonitor.cpp:259] Connect to Spark for neighbor events
I1221 18:27:36.502368 25431 PosixThreadFactory.cpp:194] setpriority failed (are you root?) with error 13: Permission denied
I1221 18:27:36.504649 25439 ThreadManager.tcc:374] ThreadManager::add called with numa == true, but not a NumaThreadManager
I1221 18:27:37.515449 25439 Cpp2Connection.cpp:151] Task killed due to channel close: [::1]:52316
E1221 18:27:37.515528 25418 LinkMonitor.cpp:1057] Failed to sync LinkDb from NetlinkSystemHandler. Error: apache::thrift::transport::TTransportException: Timed Out
I1221 18:27:37.515786 25441 Main.cpp:673] Starting LinkMonitor thread...
I1221 18:27:37.518009 25441 LinkMonitor.cpp:160] Loaded link-monitor config from disk.
I1221 18:27:37.518066 25441 LinkMonitor.cpp:54] LinkMonitor config .... 
I1221 18:27:37.518082 25441 LinkMonitor.cpp:55] 	nodeLabel: 1
I1221 18:27:37.518116 25441 LinkMonitor.cpp:56] 	isOverloaded: false
I1221 18:27:37.520366 25442 Main.cpp:703] Starting Decision thread...
I1221 18:27:37.522626 25418 Fib.cpp:123] Fib thread attaching socket/timeout callbacks...
I1221 18:27:37.524865 25443 Main.cpp:728] Starting FIB thread ...
I1221 18:27:37.524992 25418 Main.cpp:764] Starting main event loop...
I1221 18:27:37.531600 25441 LinkMonitor.cpp:474] InterfaceDb Sync is successful
I1221 18:27:38.522945 25443 AsyncSocket.cpp:2178] AsyncSocket::handleConnect(this=0x7f867c001040, fd=133 host=[::1]:60100) exception: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)
E1221 18:27:38.523689 25443 Fib.cpp:68] Failed to make thrift call to Switch Agent. Error: apache::thrift::transport::TTransportException: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused): Connection refused
I1221 18:27:39.523697 25443 AsyncSocket.cpp:2178] AsyncSocket::handleConnect(this=0x7f867c001040, fd=133 host=[::1]:60100) exception: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)
E1221 18:27:39.524235 25443 Fib.cpp:68] Failed to make thrift call to Switch Agent. Error: apache::thrift::transport::TTransportException: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused): Connection refused
^CI1221 18:27:39.969753 25418 AsyncSignalHandler.cpp:43] AsyncSignalHandler: Received signal 2
I1221 18:27:39.969815 25418 StopEventLoopSignalHandler.h:29] Received signal: 2. Stopping event loop ...
I1221 18:27:39.969877 25418 Main.cpp:766] Main event loop got stopped
I1221 18:27:39.969970 25442 Main.cpp:706] Decision thread got stopped.
I1221 18:27:39.970103 25441 Main.cpp:676] LinkMonitor thread got stopped.
I1221 18:27:39.970140 25429 Main.cpp:572] Spark thread got stopped.
I1221 18:27:39.970183 25443 Main.cpp:731] FIB thread got stopped.
I1221 18:27:39.970232 25428 Main.cpp:505] PrefixManager thread got stopped.
I1221 18:27:39.970453 25426 Main.cpp:481] KvStore thread got stopped.
I1221 18:27:39.970551 25425 Main.cpp:456] ZmqMonitor thread got stopped.
I1221 18:27:39.970655 25424 Main.cpp:436] ConfigStore thread got stopped.
I1221 18:27:39.970696 25421 Main.cpp:369] Watchdog thread got stopped.
I1221 18:27:39.972223 25439 Acceptor.cpp:451] Dropping all connections from Acceptor=0x7f8684009a90 in thread 0x7f8654000b00
I1221 18:27:39.973006 25423 Main.cpp:411] NetlinkSystem server got stopped.
openr[25418]: Stopping OpenR daemon.

# What's the expected result?

-:)
Thanks!

**Comment by saifhhasan** [comment]
```
./run_openr.sh: line 77: /etc/sysconfig/openr: 没有那个文件或目录
Configuration not found at /etc/sysconfig/openr. Using default configuration
```
You can optionally configure Open/R as per documentation in [Runbook.md](https://github.com/facebook/openr/blob/master/openr/docs/Runbook.md) and place it at `/etc/sysconfig/openr` ... If you don't provide custom configuration it will fall back to use default configuration as per specification in `run_openr.sh`

Closing issue. Feel free to open it back again if you think I missed something.

**Comment by mjena** [comment]
Hi @saifhhasan , 
if changes are needed to make the run_openr.sh work, then it will be great if those changes are mentioned clearly in the documentation.
the documentation just says, to execute run_openr.sh with some basic example.

the issue which is mentioned above (socket connection refused) is very basic and easy to reproduce.
Is it possible that run_openr.sh script was added without proper testing?
It will be great if a working run script is provided which can be really helpful for a newbie who wants to understand how openr works.
