### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by bodleytunes** [facebook/openr#2]
Hi All,

I downloaded this and tried to compile, firstly on Debian 8 Jessie and then on Ubuntu 17.04, but both fail in the same place.  I've not yet tried 16.04 though.

I used the provided install script.

It seems to be around the spark.cpp section:

`/home/jon/openr/openr/spark/Spark.cpp: In member function ‘void openr::Spark::prepare(folly::Optional<int>)’:
/home/jon/openr/openr/spark/Spark.cpp:445:66: error: throw will always call terminate() [-Werror=terminate]
         "Failed creating UDP socket: {}", folly::errnoStr(errno)));`

![image](https://user-images.githubusercontent.com/619239/32944110-3fc04ebc-cb86-11e7-86b8-b2c4a0df2a92.png)

Cheers :)

Jon.

**Comment by saifhhasan** [comment]
Hello @bodleytunes .. It seems that you are using newer gcc version to compile the code. We are not there yet but I hope to take out those error over the weekend.

Meanwhile Can you add `-Wno-terminate` to CXXFLAGS and try to compile the code as a work-around for quick build? 

Example:
https://github.com/facebook/openr/blob/master/openr/CMakeLists.txt#L6

**Comment by bodleytunes** [comment]
Ok will give it a try, cheers 👍

**Comment by bodleytunes** [comment]
Hi Tried that and now get this:

![image](https://user-images.githubusercontent.com/619239/32982405-3795d80a-cc7c-11e7-8bb4-64f9647b23e8.png)

**Comment by bodleytunes** [comment]
`depbase=`echo futures/Future.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/include    -std=gnu++1y -g -O2 -MT futures/Future.lo -MD -MP -MF $depbase.Tpo -c -o futures/Future.lo futures/Future.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++1y -g -O2 -MT futures/Future.lo -MD -MP -MF futures/.deps/Future.Tpo -c futures/Future.cpp  -fPIC -DPIC -o futures/.libs/Future.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
Makefile:2156: recipe for target 'futures/Future.lo' failed
make[2]: *** [futures/Future.lo] Error 1
make[2]: Leaving directory '/home/jon/openr/build/deps/folly/folly'
Makefile:2275: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/jon/openr/build/deps/folly/folly'
Makefile:1302: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by bodleytunes** [comment]
Added that flag in cmakelists.txt

![image](https://user-images.githubusercontent.com/619239/32982416-73f11f3a-cc7c-11e7-907e-2dcc0693ff18.png)

**Comment by bodleytunes** [comment]
I'm trying again on a vm with more memory... will report back.

**Comment by bodleytunes** [comment]
OK got much further now but seems to have failed doing the tests, speicifically netlinksubscribertest:
:(

![image](https://user-images.githubusercontent.com/619239/32982746-24dff7ae-cc81-11e7-81e1-3b0aee56b917.png)

**Comment by saifhhasan** [comment]
This is great. You can now run and test OpenR on physical topology. We will soon provide Emulation tool to test in virtual topology (but it can take several weeks before it will be out ... checkout docs/Emulator.md)

Can you please provide me with what went wrong on netlink-susbcriber test by running it manually (it should be present in build directory). I will try to get it fixed.

**Comment by bodleytunes** [comment]
I've attached the testing log file, let me know if this is the right one.

Cheers,
Jon.
[tests.log](https://github.com/facebook/openr/files/1485495/tests.log)

**Comment by bodleytunes** [comment]
Seems to be running now, I'm using the script to run it.

Are there any included SystemD unit files so it can run as a service?

Cheers,
Jon.

**Comment by bodleytunes** [comment]
Ah should have rtfm its in the runbook.md :)

**Comment by bodleytunes** [comment]
Hi,

One more thing, logs seem to be peppered with these error messages, just wondering if this is something to be worried about.

`Nov 20 08:26:27 hub2-proxhub2-prox openr[23957]: E1120 08:26:27.413861 23985 Fib.cpp:420] Failed to sync routeDb with switch FIB agent. Error: apache::thrift::transport::TTransportException: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused): Connection refused
Nov 20 08:26:27 hub2-proxhub2-prox openr[23957]: I1120 08:26:27.828816 23985 AsyncSocket.cpp:2143] AsyncSocket::handleConnect(this=0x7fc6a0002250, fd=130 host=[::1]:60100) exception: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)
Nov 20 08:26:27 hub2-proxhub2-prox openr[23957]: E1120 08:26:27.829002 23985 Fib.cpp:70] Failed to make thrift call to Switch Agent. Error: apache::thrift::transport::TTransportException: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused): Connection refused
Nov 20 08:26:28 hub2-proxhub2-prox openr[23957]: I1120 08:26:28.829386 23985 AsyncSocket.cpp:2143] AsyncSocket::handleConnect(this=0x7fc6a0002250, fd=130 host=[::1]:60100) exception: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)
Nov 20 08:26:28 hub2-proxhub2-prox openr[23957]: E1120 08:26:28.829690 23985 Fib.cpp:70] Failed to make thrift call to Switch Agent. Error: apache::thrift::transport::TTransportException: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused): Connection refused
Nov 20 08:26:29 hub2-proxhub2-prox openr[23957]: I1120 08:26:29.829759 23985 AsyncSocket.cpp:2143] AsyncSocket::handleConnect(this=0x7fc6a0002250, fd=130 host=[::1]:60100) exception: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)
Nov 20 08:26:29 hub2-proxhub2-prox openr[23957]: E1120 08:26:29.830052 23985 Fib.cpp:70] Failed to make thrift call to Switch Agent. Error: apache::thrift::transport::TTransportException: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused): Connection refused
Nov 20 08:26:30 hub2-proxhub2-prox openr[23957]: I1120 08:26:30.830761 23985 AsyncSocket.cpp:2143] AsyncSocket::handleConnect(this=0x7fc6a0002250, fd=130 host=[::1]:60100) exception: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)
Nov 20 08:26:30 hub2-proxhub2-prox openr[23957]: E1120 08:26:30.831017 23985 Fib.cpp:70] Failed to make thrift call to Switch Agent. Error: apache::thrift::transport::TTransportException: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused): Connection refused
Nov 20 08:26:31 hub2-proxhub2-prox openr[23957]: I1120 08:26:31.509306 23985 Fib.cpp:371] Syncing latest routeDb with fib-agent ...
Nov 20 08:26:31 hub2-proxhub2-prox openr[23957]: I1120 08:26:31.509865 23985 AsyncSocket.cpp:2143] AsyncSocket::handleConnect(this=0x7fc6a0002250, fd=130 host=[::1]:60100) exception: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)`

Cheers,

Jon.

**Comment by saifhhasan** [comment]
The error log you see above are legit. You are running OpenR in non-dryrun mode (which means it will program routes or tries to talk to FibAgent) and expects `FibService` to be up and running. 

OpenR by default comes with `NetlinkFibHandler` which implements `FibService` and programs routes into the linux. You can enable it explicitly via [ENABLE_NETLINK_FIB_HANDLER](https://github.com/facebook/openr/blob/master/openr/docs/Runbook.md#enable_netlink_fib_handler) option

I have internally submitted a patch to address build error you are getting as well as fixing `netlink_subscriber_test` unittest. Once landed I will close this issue.

**Comment by bodleytunes** [comment]
OK thanks I'll try that option.
Jon.

**Comment by saifhhasan** [comment]
Commit https://github.com/facebook/openr/commit/210640153a37d8a4912db0d5be7da4cf72abb54b#diff-304d33f4448afe5d095ce2e660da325b will address the issue here.
