### ISSUE TITLE
Unused options error in make_docker_context.py

### ISSUE THREAD

**Issue by jeroen-dhollander** [facebook/openr#23]
# Issue Description

When running `make_docker_context.py`, it fails with an `Unused options` error

# Environment

* tag or commit hash on which this occured
   master
* OS version: <e.g. ubuntu-16.04>
   CentOS 7
...

# Minimal test code / Steps to reproduce the issue

Just run `./make_docker_context.py` in `build/fbcode_builder`

# What's the actual result?
```
/tmp/openr/build/fbcode_builder (master %=) > ./make_docker_context.py 
INFO: Docker ccache not enabled
Traceback (most recent call last):
  File "./make_docker_context.py", line 173, in <module>
    config['github_project'],
  File "./make_docker_context.py", line 154, in make_docker_context
    dockerfile = builder.render(get_steps_fn(builder))
  File "/tmp/openr/build/fbcode_builder/fbcode_builder.py", line 136, in render
    .format(unused_options)
RuntimeError: Unused options: set([u'prefix', u'make_parallelism', u'projects_dir']) -- please check if you made a typo in any of them. Those that are truly not useful should be not be set so that this typo detection can be useful.
```

# What's the expected result?

No error and the Dockerfile is generated.

Note: If I simply remove that unused options check the Dockerfile is generated (but I think it then ignores those 3 options).

**Comment by jstrizich** [comment]
this is a bit of ugliness. you need to run that command from the parent directory (`openr/build/`) to pick up the fbcode_builder_config.py that lives there. The one in `openr/build/fbcode_builder` is usesd so the command works for --help

**Comment by jeroen-dhollander** [comment]
Thank you, running it from the parent directory solved the errors.
