### ISSUE TITLE
Link error shown(libsecurity.so)  during compilation in Ubuntu 16.04

### ISSUE THREAD

**Issue by doc321** [facebook/openr#30]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue Description
Compile Error 

Just clone a Open/R code from github, and execute "sudo bash ./build_openr.sh", one compile issue about "/usr/local/lib/libsecurity.so: undefined reference to `error_message(long)" is shown.

Deleted dir linux_monitor/tests to bypass the issue,  build_openr.sh can finish, but when "make install" this same issue will show again when link platform_linux.

# Environment

* tag or commit hash on which this occured
* OS version: <e.g. ubuntu-16.04>
...
A new installed Ubuntu 16.04 on VirtualBox

# Minimal test code / Steps to reproduce the issue

# What's the actual result?
<include assertion message or callstack if applicable>

...........
+ install_openr
+ pushd .
/tmp/openr/openr-master/build/deps /tmp/openr/openr-master/build/deps
+ cd /tmp/openr/openr-master/build
+ cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=ON -DADD_ROOT_TESTS=ON -DCMAKE_CXX_FLAGS=-Wno-unused-parameter ../openr/
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Thrift will create the Object file : LinuxPlatform-cpp2-obj
Thrift will create the Object file : PersistentStore-cpp2-obj
Thrift will create the Object file : KvStore-cpp2-obj
Thrift will create the Object file : Lsdb-cpp2-obj
Thrift will create the Object file : IpPrefix-cpp2-obj
Thrift will create the Object file : Fib-cpp2-obj
Thrift will create the Object file : KnownKeys-cpp2-obj
Thrift will create the Object file : HealthChecker-cpp2-obj
Thrift will create the Object file : LinkMonitor-cpp2-obj
Thrift will create the Object file : Platform-cpp2-obj
Thrift will create the Object file : Spark-cpp2-obj
Thrift will create the Object file : AllocPrefix-cpp2-obj
Thrift will create the Object file : PrefixManager-cpp2-obj
Thrift will create the Object file : Decision-cpp2-obj
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/openr/openr-master/build
+ make
Scanning dependencies of target Spark-cpp2-target
[  1%] Generating Spark files. Output: /tmp/openr/openr-master/build/thrift-out/openr/if
[  1%] Built target Spark-cpp2-target
Scanning dependencies of target IpPrefix-cpp2-target
[  2%] Generating IpPrefix files. Output: /tmp/openr/openr-master/build/thrift-out/openr/if
[  2%] Built target IpPrefix-cpp2-target
Scanning dependencies of target IpPrefix-cpp2-obj
[  3%] Building CXX object CMakeFiles/IpPrefix-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/IpPrefix_constants.cpp.o
[  3%] Building CXX object CMakeFiles/IpPrefix-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/IpPrefix_data.cpp.o
[  4%] Building CXX object CMakeFiles/IpPrefix-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/IpPrefix_types.cpp.o
[  5%] Built target IpPrefix-cpp2-obj
Scanning dependencies of target Platform-cpp2-target
[  6%] Generating Platform files. Output: /tmp/openr/openr-master/build/thrift-out/openr/if
[  6%] Built target Platform-cpp2-target
Scanning dependencies of target Platform-cpp2-obj
[  7%] Building CXX object CMakeFiles/Platform-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/Platform_constants.cpp.o
[  7%] Building CXX object CMakeFiles/Platform-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/Platform_data.cpp.o
[  8%] Building CXX object CMakeFiles/Platform-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/Platform_types.cpp.o
[  9%] Building CXX object CMakeFiles/Platform-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/FibService.cpp.o
[  9%] Building CXX object CMakeFiles/Platform-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/FibService_client.cpp.o
[ 10%] Building CXX object CMakeFiles/Platform-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/SystemService.cpp.o
[ 10%] Building CXX object CMakeFiles/Platform-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/SystemService_client.cpp.o
[ 11%] Built target Platform-cpp2-obj
Scanning dependencies of target AllocPrefix-cpp2-target
[ 12%] Generating AllocPrefix files. Output: /tmp/openr/openr-master/build/thrift-out/openr/if
[ 12%] Built target AllocPrefix-cpp2-target
Scanning dependencies of target AllocPrefix-cpp2-obj
[ 13%] Building CXX object CMakeFiles/AllocPrefix-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/AllocPrefix_constants.cpp.o
[ 13%] Building CXX object CMakeFiles/AllocPrefix-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/AllocPrefix_data.cpp.o
[ 14%] Building CXX object CMakeFiles/AllocPrefix-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/AllocPrefix_types.cpp.o
[ 14%] Built target AllocPrefix-cpp2-obj
Scanning dependencies of target Lsdb-cpp2-target
[ 15%] Generating Lsdb files. Output: /tmp/openr/openr-master/build/thrift-out/openr/if
[ 15%] Built target Lsdb-cpp2-target
Scanning dependencies of target Lsdb-cpp2-obj
[ 16%] Building CXX object CMakeFiles/Lsdb-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/Lsdb_constants.cpp.o
[ 17%] Building CXX object CMakeFiles/Lsdb-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/Lsdb_data.cpp.o
[ 17%] Building CXX object CMakeFiles/Lsdb-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/Lsdb_types.cpp.o
[ 17%] Built target Lsdb-cpp2-obj
Scanning dependencies of target LinkMonitor-cpp2-target
[ 17%] Generating LinkMonitor files. Output: /tmp/openr/openr-master/build/thrift-out/openr/if
[ 17%] Built target LinkMonitor-cpp2-target
Scanning dependencies of target Spark-cpp2-obj
[ 18%] Building CXX object CMakeFiles/Spark-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/Spark_constants.cpp.o
[ 18%] Building CXX object CMakeFiles/Spark-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/Spark_data.cpp.o
[ 19%] Building CXX object CMakeFiles/Spark-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/Spark_types.cpp.o
[ 20%] Built target Spark-cpp2-obj
Scanning dependencies of target LinkMonitor-cpp2-obj
[ 20%] Building CXX object CMakeFiles/LinkMonitor-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/LinkMonitor_constants.cpp.o
[ 21%] Building CXX object CMakeFiles/LinkMonitor-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/LinkMonitor_data.cpp.o
[ 22%] Building CXX object CMakeFiles/LinkMonitor-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/LinkMonitor_types.cpp.o
[ 23%] Built target LinkMonitor-cpp2-obj
Scanning dependencies of target KnownKeys-cpp2-target
[ 24%] Generating KnownKeys files. Output: /tmp/openr/openr-master/build/thrift-out/openr/if
[ 24%] Built target KnownKeys-cpp2-target
Scanning dependencies of target KnownKeys-cpp2-obj
[ 25%] Building CXX object CMakeFiles/KnownKeys-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/KnownKeys_constants.cpp.o
[ 26%] Building CXX object CMakeFiles/KnownKeys-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/KnownKeys_data.cpp.o
[ 26%] Building CXX object CMakeFiles/KnownKeys-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/KnownKeys_types.cpp.o
[ 26%] Built target KnownKeys-cpp2-obj
Scanning dependencies of target HealthChecker-cpp2-target
[ 26%] Generating HealthChecker files. Output: /tmp/openr/openr-master/build/thrift-out/openr/if
[ 26%] Built target HealthChecker-cpp2-target
Scanning dependencies of target HealthChecker-cpp2-obj
[ 26%] Building CXX object CMakeFiles/HealthChecker-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/HealthChecker_constants.cpp.o
[ 27%] Building CXX object CMakeFiles/HealthChecker-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/HealthChecker_data.cpp.o
[ 28%] Building CXX object CMakeFiles/HealthChecker-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/HealthChecker_types.cpp.o
[ 29%] Built target HealthChecker-cpp2-obj
Scanning dependencies of target Fib-cpp2-target
[ 29%] Generating Fib files. Output: /tmp/openr/openr-master/build/thrift-out/openr/if
[ 29%] Built target Fib-cpp2-target
Scanning dependencies of target Fib-cpp2-obj
[ 29%] Building CXX object CMakeFiles/Fib-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/Fib_constants.cpp.o
[ 30%] Building CXX object CMakeFiles/Fib-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/Fib_data.cpp.o
[ 31%] Building CXX object CMakeFiles/Fib-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/Fib_types.cpp.o
[ 32%] Built target Fib-cpp2-obj
Scanning dependencies of target KvStore-cpp2-target
[ 33%] Generating KvStore files. Output: /tmp/openr/openr-master/build/thrift-out/openr/if
[ 33%] Built target KvStore-cpp2-target
Scanning dependencies of target KvStore-cpp2-obj
[ 33%] Building CXX object CMakeFiles/KvStore-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/KvStore_constants.cpp.o
[ 34%] Building CXX object CMakeFiles/KvStore-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/KvStore_data.cpp.o
[ 34%] Building CXX object CMakeFiles/KvStore-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/KvStore_types.cpp.o
[ 35%] Built target KvStore-cpp2-obj
Scanning dependencies of target PersistentStore-cpp2-target
[ 35%] Generating PersistentStore files. Output: /tmp/openr/openr-master/build/thrift-out/openr/if
[ 35%] Built target PersistentStore-cpp2-target
Scanning dependencies of target PersistentStore-cpp2-obj
[ 35%] Building CXX object CMakeFiles/PersistentStore-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/PersistentStore_constants.cpp.o
[ 36%] Building CXX object CMakeFiles/PersistentStore-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/PersistentStore_data.cpp.o
[ 37%] Building CXX object CMakeFiles/PersistentStore-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/PersistentStore_types.cpp.o
[ 38%] Built target PersistentStore-cpp2-obj
Scanning dependencies of target LinuxPlatform-cpp2-target
[ 39%] Generating LinuxPlatform files. Output: /tmp/openr/openr-master/build/thrift-out/openr/if
[ 39%] Built target LinuxPlatform-cpp2-target
Scanning dependencies of target LinuxPlatform-cpp2-obj
[ 40%] Building CXX object CMakeFiles/LinuxPlatform-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/LinuxPlatform_constants.cpp.o
[ 40%] Building CXX object CMakeFiles/LinuxPlatform-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/LinuxPlatform_data.cpp.o
[ 41%] Building CXX object CMakeFiles/LinuxPlatform-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/LinuxPlatform_types.cpp.o
[ 42%] Building CXX object CMakeFiles/LinuxPlatform-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/LinuxFibService.cpp.o
[ 42%] Building CXX object CMakeFiles/LinuxPlatform-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/LinuxFibService_client.cpp.o
[ 43%] Built target LinuxPlatform-cpp2-obj
Scanning dependencies of target PrefixManager-cpp2-target
[ 43%] Generating PrefixManager files. Output: /tmp/openr/openr-master/build/thrift-out/openr/if
[ 43%] Built target PrefixManager-cpp2-target
Scanning dependencies of target PrefixManager-cpp2-obj
[ 43%] Building CXX object CMakeFiles/PrefixManager-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/PrefixManager_constants.cpp.o
[ 44%] Building CXX object CMakeFiles/PrefixManager-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/PrefixManager_data.cpp.o
[ 45%] Building CXX object CMakeFiles/PrefixManager-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/PrefixManager_types.cpp.o
[ 46%] Built target PrefixManager-cpp2-obj
Scanning dependencies of target Decision-cpp2-target
[ 47%] Generating Decision files. Output: /tmp/openr/openr-master/build/thrift-out/openr/if
[ 47%] Built target Decision-cpp2-target
Scanning dependencies of target Decision-cpp2-obj
[ 48%] Building CXX object CMakeFiles/Decision-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/Decision_constants.cpp.o
[ 49%] Building CXX object CMakeFiles/Decision-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/Decision_data.cpp.o
[ 49%] Building CXX object CMakeFiles/Decision-cpp2-obj.dir/thrift-out/openr/if/gen-cpp2/Decision_types.cpp.o
[ 49%] Built target Decision-cpp2-obj
Scanning dependencies of target openrlib
[ 50%] Building CXX object CMakeFiles/openrlib.dir/allocators/PrefixAllocator.cpp.o
[ 51%] Building CXX object CMakeFiles/openrlib.dir/common/BuildInfo.cpp.o
[ 51%] Building CXX object CMakeFiles/openrlib.dir/common/KnownKeysStore.cpp.o
[ 52%] Building CXX object CMakeFiles/openrlib.dir/common/ExponentialBackoff.cpp.o
[ 53%] Building CXX object CMakeFiles/openrlib.dir/common/Util.cpp.o
[ 53%] Building CXX object CMakeFiles/openrlib.dir/common/Constants.cpp.o
[ 54%] Building CXX object CMakeFiles/openrlib.dir/config-store/PersistentStore.cpp.o
[ 55%] Building CXX object CMakeFiles/openrlib.dir/config-store/PersistentStoreClient.cpp.o
[ 55%] Building CXX object CMakeFiles/openrlib.dir/decision/Decision.cpp.o
[ 56%] Building CXX object CMakeFiles/openrlib.dir/fib/Fib.cpp.o
[ 57%] Building CXX object CMakeFiles/openrlib.dir/health-checker/HealthChecker.cpp.o
[ 57%] Building CXX object CMakeFiles/openrlib.dir/kvstore/KvStoreClient.cpp.o
[ 58%] Building CXX object CMakeFiles/openrlib.dir/kvstore/KvStore.cpp.o
[ 58%] Building CXX object CMakeFiles/openrlib.dir/kvstore/KvStoreWrapper.cpp.o
[ 59%] Building CXX object CMakeFiles/openrlib.dir/link-monitor/LinkMonitor.cpp.o
[ 60%] Building CXX object CMakeFiles/openrlib.dir/nl/NetlinkRouteSocket.cpp.o
[ 60%] Building CXX object CMakeFiles/openrlib.dir/nl/NetlinkSubscriber.cpp.o
[ 61%] Building CXX object CMakeFiles/openrlib.dir/platform/NetlinkFibHandler.cpp.o
[ 62%] Building CXX object CMakeFiles/openrlib.dir/platform/NetlinkSystemHandler.cpp.o
[ 62%] Building CXX object CMakeFiles/openrlib.dir/platform/PlatformPublisher.cpp.o
[ 63%] Building CXX object CMakeFiles/openrlib.dir/prefix-manager/PrefixManager.cpp.o
[ 64%] Building CXX object CMakeFiles/openrlib.dir/prefix-manager/PrefixManagerClient.cpp.o
[ 64%] Building CXX object CMakeFiles/openrlib.dir/spark/IoProvider.cpp.o
[ 65%] Building CXX object CMakeFiles/openrlib.dir/spark/SparkWrapper.cpp.o
[ 66%] Building CXX object CMakeFiles/openrlib.dir/spark/Spark.cpp.o
[ 66%] Building CXX object CMakeFiles/openrlib.dir/watchdog/Watchdog.cpp.o
[ 67%] Linking CXX static library libopenrlib.a
[ 67%] Built target openrlib
Scanning dependencies of target decision_test
[ 67%] Building CXX object CMakeFiles/decision_test.dir/decision/tests/DecisionTest.cpp.o
[ 68%] Linking CXX executable decision_test
[ 68%] Built target decision_test
Scanning dependencies of target netlink_route_socket_test
[ 68%] Building CXX object CMakeFiles/netlink_route_socket_test.dir/nl/tests/NetlinkRouteSocketTest.cpp.o
[ 69%] Linking CXX executable netlink_route_socket_test
[ 69%] Built target netlink_route_socket_test
Scanning dependencies of target health_checker_test
[ 70%] Building CXX object CMakeFiles/health_checker_test.dir/health-checker/tests/HealthCheckerTest.cpp.o
[ 71%] Linking CXX executable health_checker_test
[ 71%] Built target health_checker_test
Scanning dependencies of target link_monitor_test
[ 71%] Building CXX object CMakeFiles/link_monitor_test.dir/link-monitor/tests/LinkMonitorTest.cpp.o
[ 72%] Building CXX object CMakeFiles/link_monitor_test.dir/link-monitor/tests/MockNetlinkSystemHandler.cpp.o
[ 72%] Linking CXX executable link_monitor_test
/usr/local/lib/libsecurity.so: undefined reference to `error_message(long)'
collect2: error: ld returned 1 exit status
CMakeFiles/link_monitor_test.dir/build.make:143: recipe for target 'link_monitor_test' failed
make[2]: *** [link_monitor_test] Error 1
CMakeFiles/Makefile2:554: recipe for target 'CMakeFiles/link_monitor_test.dir/all' failed
make[1]: *** [CMakeFiles/link_monitor_test.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
abc@abc-VirtualBox:/tmp/openr/openr-master/build$ 

# What's the expected result?
Compile Successfully

**Comment by saifhhasan** [comment]
This should be fixed now with https://github.com/facebook/openr/commit/96d4957b68f03668b880f733de416e50fdb0fc72 .. You can pull latest and resume your build :)
