### ISSUE TITLE
Still have same issue as link error shown(libsecurity.so) during compilation in Ubuntu 16.04 

### ISSUE THREAD

**Issue by doc321** [facebook/openr#31]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue Description
Still have same issue as link error shown(libsecurity.so) during compilation in Ubuntu 16.04 
after try on 6/10 version

# Environment

* tag or commit hash on which this occured
* OS version: <e.g. ubuntu-16.04>
...
Ubuntu-16.04 on VitrualBox

# Minimal test code / Steps to reproduce the issue
sudo bash build_openr.sh

# What's the actual result?
<include assertion message or callstack if applicable>
[ 69%] Linking CXX executable netlink_route_socket_test
[ 69%] Built target netlink_route_socket_test
Scanning dependencies of target health_checker_test
[ 70%] Building CXX object CMakeFiles/health_checker_test.dir/health-checker/tests/HealthCheckerTest.cpp.o
[ 71%] Linking CXX executable health_checker_test
[ 71%] Built target health_checker_test
Scanning dependencies of target link_monitor_test
[ 71%] Building CXX object CMakeFiles/link_monitor_test.dir/link-monitor/tests/LinkMonitorTest.cpp.o
[ 72%] Building CXX object CMakeFiles/link_monitor_test.dir/link-monitor/tests/MockNetlinkSystemHandler.cpp.o
[ 72%] Linking CXX executable link_monitor_test
/usr/local/lib/libsecurity.so: undefined reference to `error_message(long)'
collect2: error: ld returned 1 exit status
CMakeFiles/link_monitor_test.dir/build.make:143: recipe for target 'link_monitor_test' failed
make[2]: *** [link_monitor_test] Error 1
CMakeFiles/Makefile2:554: recipe for target 'CMakeFiles/link_monitor_test.dir/all' failed
make[1]: *** [CMakeFiles/link_monitor_test.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

# What's the expected result?

Compile Successfully

**Comment by saifhhasan** [comment]
Oh .. I fixed workflow for fbcode_builder. If you pull latest krb5 library from source, build it and install it and follow open/r build workflow then it should succeed.

https://github.com/facebook/openr/commit/c6f6b638918bc74853615ec1405dad1584adc51b will do that for you. Pull latest code and try building again. If it succeed you can close this task, if it fails we would encourage you contribute pull request fixes if you have cycles for it.

**Comment by doc321** [comment]
Clone the lastest code, compile successfully now. Thanks your new commit,  Saifhhasan.
