### ISSUE TITLE
Test in Python 2 + Python 3 with Travis/GitHub Action

### ISSUE THREAD

**Issue by cooperlees** [facebook/openr#35]
# Issue Description
- Can we please have travis test Python aspects of OpenR in both Python 2 and Python 3.

# Environment
In you Ubuntu travis environment should be enough

# Minimal test code / Steps to reproduce the issue
- No repro, just want to see things tested in both Python versions.

# What's the actual result?
Travis showing that Python aspects pass in both versions or only Python 3 (as far as I am concerned 👍)

# What's the expected result?
Python 3 first.

**Comment by saifhhasan** [comment]
We will look into this as we are now fully supporting python3

**Comment by saifhhasan** [comment]
It's been a while. Coming back to this again. Can you spare a cycle to help us setting this up ? Thanks :)

**Comment by cooperlees** [comment]
I'll make sure we have a GitHub action checking this.

**Comment by cooperlees** [comment]
Will take care of this in #56
