### ISSUE TITLE
Update workflow for One Step Build  

### ISSUE THREAD

**Issue by butjar** [facebook/openr#40]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue Description
According to https://github.com/facebook/openr/issues/38#issuecomment-442628317 the one-step build script `build_openr.sh` is not maintained. 

# Environment

* tag or commit hash on which this occurred: 6ccda74be02fd0393b770b90a6968cb93bd5a62a
* OS version: ubuntu-16.04 server

# Minimal test code / Steps to reproduce the issue
```
cd build
sudo bash ./build_openr.sh
```

# What's the actual result?
Several issues during build, mainly because not all of the dependencies are frozen. 

# What's the expected result?
The build should succeed and OpenR and all dependencies included in the build are installed.

**Comment by butjar** [comment]
I created a gist including a script to generate the build script from `fbcode_builder`: https://gist.github.com/butjar/177871dc7abc7f98c71bcb1dc66d539a.

This solution is a bit dirty and I'm willing to create a clean PR, if you guide me to a good solution. My proposal is updating `shell_builder.py` to take a parameter (e.g. --system) and return a script that installs OpenR on the system. However, as far as I understood this also requires updating `fbcode_builder.py` and I'm not sure how much you like to touch the `fbcode_builder` boilerplate code.

**Comment by saifhhasan** [comment]
@butjar - If you can try to fix error in `build_openr.sh` that will be great. Or I can take a look in few days. 

Regarding fbcode builder support, I am not much aware of it. You can send a pull request and we can try to consider it. Note that fbcode-builder (same code) is also being used in other facebook opensource projects like `folly`, `fbthrift` etc. So if you can add support for installing build artifacts from docker to system generically, then it will be an acceptable solution. Quick glancing shows that you're doing rsync for all `/lib` and `/sbin` directories, which might not be a good solution.

**Comment by butjar** [comment]
I had several problems regarding the dependencies, moreover it seems that the `github_hashes` get auto-updated. Some dependencies are not frozen at all. I think, the revisions should be build from `fbcode_builder/specs` for consistency with your main workflow. Updating `build_openr.sh` will end up in similar problems soon in my opinion.

I agree, the rsync solution is not nice, but a solution installing the artifacts from docker would probably look similar. Maybe generating a deb package from the artifacts might be a good solution.

Unfortunately, the prefix in `fbcode_builder.py` is hard-coded, that's why it can not be used for a system install. I realized, that fcode builder is boilerplate, this is why I asked before touching it. I still think the `shell_builder.py` is a good location for auto generation of the `build_openr.sh`. You might also add the script generation to your CI.
