### ISSUE TITLE
Compile again

### ISSUE THREAD

**Issue by bodleytunes** [facebook/openr#6]
Hi,

Latest version doesn't seem to want to compile:

Tried on Debian 8 and also ubuntu 17.04, seems to stop in the same place.

Getting a problem when it tries to make a reference to thrift:

`Scanning dependencies of target openrlib
[ 50%] Building CXX object CMakeFiles/openrlib.dir/allocators/PrefixAllocator.cpp.o
[ 51%] Building CXX object CMakeFiles/openrlib.dir/common/KnownKeysStore.cpp.o
[ 51%] Building CXX object CMakeFiles/openrlib.dir/common/ExponentialBackoff.cpp.o
[ 52%] Building CXX object CMakeFiles/openrlib.dir/common/Util.cpp.o
[ 53%] Building CXX object CMakeFiles/openrlib.dir/common/Constants.cpp.o
[ 53%] Building CXX object CMakeFiles/openrlib.dir/config-store/PersistentStore.cpp.o
[ 54%] Building CXX object CMakeFiles/openrlib.dir/config-store/PersistentStoreClient.cpp.o
[ 54%] Building CXX object CMakeFiles/openrlib.dir/decision/Decision.cpp.o
[ 55%] Building CXX object CMakeFiles/openrlib.dir/fib/Fib.cpp.o
[ 56%] Building CXX object CMakeFiles/openrlib.dir/health-checker/HealthChecker.cpp.o
[ 56%] Building CXX object CMakeFiles/openrlib.dir/kvstore/KvStoreClient.cpp.o
[ 57%] Building CXX object CMakeFiles/openrlib.dir/kvstore/KvStore.cpp.o
[ 57%] Building CXX object CMakeFiles/openrlib.dir/kvstore/KvStoreWrapper.cpp.o
[ 58%] Building CXX object CMakeFiles/openrlib.dir/link-monitor/LinkMonitor.cpp.o
[ 59%] Building CXX object CMakeFiles/openrlib.dir/nl/NetlinkIfSocket.cpp.o
[ 59%] Building CXX object CMakeFiles/openrlib.dir/nl/NetlinkRouteSocket.cpp.o
[ 60%] Building CXX object CMakeFiles/openrlib.dir/nl/NetlinkSubscriber.cpp.o
[ 60%] Building CXX object CMakeFiles/openrlib.dir/platform/NetlinkFibHandler.cpp.o
[ 61%] Building CXX object CMakeFiles/openrlib.dir/platform/NetlinkSystemHandler.cpp.o
[ 62%] Building CXX object CMakeFiles/openrlib.dir/platform/PlatformPublisher.cpp.o
[ 62%] Building CXX object CMakeFiles/openrlib.dir/prefix-manager/PrefixManager.cpp.o
[ 63%] Building CXX object CMakeFiles/openrlib.dir/prefix-manager/PrefixManagerClient.cpp.o
[ 64%] Building CXX object CMakeFiles/openrlib.dir/spark/IoProvider.cpp.o
[ 64%] Building CXX object CMakeFiles/openrlib.dir/spark/SparkWrapper.cpp.o
[ 65%] Building CXX object CMakeFiles/openrlib.dir/spark/Spark.cpp.o
[ 65%] Linking CXX static library libopenrlib.a
[ 65%] Built target openrlib
Scanning dependencies of target fib_test
[ 66%] Building CXX object CMakeFiles/fib_test.dir/fib/tests/FibTest.cpp.o
[ 66%] Building CXX object CMakeFiles/fib_test.dir/fib/tests/MockNetlinkFibHandler.cpp.o
[ 67%] Linking CXX executable fib_test
/usr/local/lib/libthriftcpp2.so: undefined reference to `apache::thrift::RequestRpcMetadata::~RequestRpcMetadata()'
collect2: error: ld returned 1 exit status
CMakeFiles/fib_test.dir/build.make:138: recipe for target 'fib_test' failed
make[2]: *** [fib_test] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/fib_test.dir/all' failed
make[1]: *** [CMakeFiles/fib_test.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
root@hub2-proxhub2-prox /home/jon/openr/build # `

![image](https://user-images.githubusercontent.com/619239/33096134-da3debc8-cefd-11e7-8225-5f41d77cfcaf.png)

**Comment by cmpt-mnt** [comment]
I had same issue and error messages on Ubuntu16.04...

**Comment by jstrizich** [comment]
Hi @bodleytunes , @cmpt-mnt: addressing this now. should have a fix by tomorrow

**Comment by bodleytunes** [comment]
OK cheers :)

**Comment by jstrizich** [comment]
this is landed [here](https://github.com/facebook/fbthrift/commit/b79ec91c17e7c96ffc247d90f6c475d3ca2a0be0)

**Comment by bodleytunes** [comment]
Hi

I just updated the repo with a git pull and tried install again but now get this :(

`Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/lib/libmstch.a
-- Up-to-date: /usr/local/include/mstch/mstch.hpp
-- Up-to-date: /usr/local/lib/cmake/mstch/mstch-targets.cmake
-- Installing: /usr/local/lib/cmake/mstch/mstch-targets-release.cmake
-- Up-to-date: /usr/local/lib/cmake/mstch/mstch-config.cmake
-- Up-to-date: /usr/local/lib/cmake/mstch/mstch-config-version.cmake
+ ldconfig
+ popd
/home/jon/openr/build/deps
+ install_zstd
+ pushd .
/home/jon/openr/build/deps /home/jon/openr/build/deps
+ [[ ! -e zstd ]]
+ cd zstd
+ make
make[1]: Entering directory '/home/jon/openr/build/deps/zstd/lib'
make[1]: Nothing to be done for 'default'.
make[1]: Leaving directory '/home/jon/openr/build/deps/zstd/lib'
make[1]: Entering directory '/home/jon/openr/build/deps/zstd/programs'
make[1]: Nothing to be done for 'default'.
make[1]: Leaving directory '/home/jon/openr/build/deps/zstd/programs'
cp programs/zstd .
+ make install
make[1]: Entering directory '/home/jon/openr/build/deps/zstd/lib'
Installing libraries
Installing includes
zstd static and shared library installed
make[1]: Leaving directory '/home/jon/openr/build/deps/zstd/lib'
make[1]: Entering directory '/home/jon/openr/build/deps/zstd/programs'
Installing binaries
Installing man pages
zstd installation completed
make[1]: Leaving directory '/home/jon/openr/build/deps/zstd/programs'
+ ldconfig
+ popd
/home/jon/openr/build/deps
+ install_folly
+ pushd .
/home/jon/openr/build/deps /home/jon/openr/build/deps
+ [[ ! -e folly ]]
++ find_github_hash facebook/folly
++ [[ 1 -eq 1 ]]
++ rev_file=github_hashes/facebook/folly-rev.txt
++ [[ -f github_hashes/facebook/folly-rev.txt ]]
++ head -1 github_hashes/facebook/folly-rev.txt
++ awk '{ print $3 }'
+ rev=ee207f19892790e091082cc7c7ab8c5df0398061
+ cd folly/folly
+ [[ ! -z ee207f19892790e091082cc7c7ab8c5df0398061 ]]
+ git checkout ee207f19892790e091082cc7c7ab8c5df0398061
fatal: reference is not a tree: ee207f19892790e091082cc7c7ab8c5df0398061`

![image](https://user-images.githubusercontent.com/619239/33276869-bab3da20-d38e-11e7-9a27-3fe4bfdf0be4.png)

**Comment by bodleytunes** [comment]
Sorry it works, re-cloned again from scratch  and is perfect.

Running tests...
Test project /home/jon/openr/build
      Start  1: OpenrSystemTest
 1/19 Test  #1: OpenrSystemTest ..................   Passed   80.68 sec
      Start  2: PrefixAllocatorTest
 2/19 Test  #2: PrefixAllocatorTest ..............   Passed    2.28 sec
      Start  3: RangeAllocatorTest
 3/19 Test  #3: RangeAllocatorTest ...............   Passed    2.42 sec
      Start  4: ExponentialBackoffTest
 4/19 Test  #4: ExponentialBackoffTest ...........   Passed    0.02 sec
      Start  5: KnownKeysStoreTest
 5/19 Test  #5: KnownKeysStoreTest ...............   Passed    0.05 sec
      Start  6: UtilTest
 6/19 Test  #6: UtilTest .........................   Passed    0.03 sec
      Start  7: PersistentStoreTest
 7/19 Test  #7: PersistentStoreTest ..............   Passed    0.02 sec
      Start  8: DecisionTest
 8/19 Test  #8: DecisionTest .....................   Passed   41.84 sec
      Start  9: HealthCheckerTest
 9/19 Test  #9: HealthCheckerTest ................   Passed   10.02 sec
      Start 10: KvStoreTest
10/19 Test #10: KvStoreTest ......................   Passed    6.76 sec
      Start 11: KvStoreClientTest
11/19 Test #11: KvStoreClientTest ................   Passed    1.67 sec
      Start 12: LinkMonitorTest
12/19 Test #12: LinkMonitorTest ..................   Passed   39.09 sec
      Start 13: FibTest
13/19 Test #13: FibTest ..........................   Passed   11.12 sec
      Start 14: NetlinkIfSocketTest
14/19 Test #14: NetlinkIfSocketTest ..............   Passed    0.11 sec
      Start 15: NetlinkRouteSocketTest
15/19 Test #15: NetlinkRouteSocketTest ...........   Passed   28.53 sec
      Start 16: NetlinkSubscriberTest
16/19 Test #16: NetlinkSubscriberTest ............   Passed    0.33 sec
      Start 17: PrefixManagerTest
17/19 Test #17: PrefixManagerTest ................   Passed    0.47 sec
      Start 18: SparkTest
18/19 Test #18: SparkTest ........................   Passed   13.98 sec
      Start 19: MockIoProviderTest
19/19 Test #19: MockIoProviderTest ...............   Passed    0.25 sec

100% tests passed, 0 tests failed out of 19

Total Test time (real) = 239.67 sec
+ popd
/home/jon/openr/build/deps
+ echo 'OpenR built and installed successfully'
OpenR built and installed successfully

Cheers!

Jon.
