### ISSUE TITLE
[question] Is NetLink a hard-dependency?

### ISSUE THREAD

**Issue by yurivict** [facebook/openr#64]
I am not able to build OpenR on FreeBSD because NetLink is a Linux kernel protocol.

Is dependency on NetLink hard, or it is possible to disable it?

Thanks,
Yuri

**Comment by GirasoleY** [comment]
Hi Yuri,

Netlink is a hard dependency now. It's integrated with LinkMonitor module.

There is a project netlink-freebsd to build netlink on FreeBSD. Not sure if can help. https://github.com/luigirizzo/netlink-freebsd

Best Regards,
Summer

**Comment by yurivict** [comment]
Thank you.
