### ISSUE TITLE
Document PolicyEngine & Config to advertise Static Routes

### ISSUE THREAD

**Issue by cooperlees** [facebook/openr#83]
# Issue Description
https://github.com/facebook/openr/commit/77040d2946d9cd92aa701501d058fe194385f630 removed LinkMonitor CLI argument for redistributing static routes.

We should document how to do this with config.

# Minimal test code / Steps to reproduce the issue
- Pass the arg and it does not work 

# What's the expected result?
Have a documented way that works for OpenR Users to share static routes.

**Comment by saifhhasan** [comment]
FYI, we're moving away from gflags and all functionality is now being supported by `OpenrConfig`. The documentation exists in the `OpenrConfig.thrift`. For this specific case you would like to populate `AreaConfig.redistribute_interfaces` field - https://github.com/facebook/openr/blob/master/openr/if/OpenrConfig.thrift#L317

**Comment by saifhhasan** [comment]
As a matter of caution, do not use any gflags for config instead specify them explicitly in the `OpenrConfig`. In next few weeks most gflags will be deprecated -- Aim is to have following as the start command

```
/bin/openr --config=/etc/sysconfig/openr.conf
```

**Comment by saifhhasan** [comment]
Oh and for advertising static routes such as `::/0`, you can use route origination feature through configuration. It should be working for simple use-case of static route advertisement, however the feature is still in progress - https://github.com/facebook/openr/blob/master/openr/if/OpenrConfig.thrift#L489

**Comment by saifhhasan** [comment]
Closing as this has been resolved.
