### ISSUE TITLE
Link to documentation is invalid

### ISSUE THREAD

**Issue by xwu64** [facebook/openr#98]
_Please use this template for reporting suspected bugs or requests for help._

# Issue Description

The link (https://openr.readthedocs.io/en/latest/) of documentation is invalid. 

# Environment

- tag or commit hash on which this occured: 80818412dae71a33ac080c97a060f4c344a2b1bc
- OS version: <e.g. ubuntu-16.04>: Any
  ...

# Minimal test code / Steps to reproduce the issue

Click link in Documentation of README file. 

# What's the actual result?

```

        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \
```

# What's the expected result?

Documentation of OpenR

**Comment by cooperlees** [comment]
Weird - https://openr.readthedocs.io/ works. Guess we just need a PR to do that.

**Comment by cooperlees** [comment]
#99 fixed this. Thanks!
